<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KShop.Commerce.ProductManagement.Domain</RootNamespace>
    <AssemblyName>KShop.Commerce.ProductManagement.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="ProductAggregate\ProductDescription.cs">
      <DependentUpon>Product.cs</DependentUpon>
    </Compile>
    <Compile Update="ProductAggregate\ProductName.cs">
      <DependentUpon>Product.cs</DependentUpon>
    </Compile>
    <Compile Update="ProductAggregate\ProductVariant.cs">
      <DependentUpon>Product.cs</DependentUpon>
    </Compile>
    <Compile Update="ProductAggregate\CurrencyCode.cs">
      <DependentUpon>Price.cs</DependentUpon>
    </Compile>
    <Compile Update="ProductAggregate\DiscountType.cs">
      <DependentUpon>Discount.cs</DependentUpon>
    </Compile>
    <Compile Update="ProductAggregate\VariantName.cs">
      <DependentUpon>ProductVariant.cs</DependentUpon>
    </Compile>
    <Compile Update="ProductAggregate\VariantSku.cs">
      <DependentUpon>ProductVariant.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="ReferenceTrimmer" Version="3.5.9"/>
  </ItemGroup>

</Project>
