// <auto-generated />
using System;
using KShop.Commerce.ProductManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KShop.Commerce.ProductManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KShop.Commerce.ProductManagement.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("KShop.Commerce.ProductManagement.Domain.ProductAggregate.Product", b =>
                {
                    b.OwnsMany("KShop.Commerce.ProductManagement.Domain.ProductAggregate.ProductVariant", "_variants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("variants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("KShop.Commerce.ProductManagement.Domain.ProductAggregate.Discount", "Discount", b2 =>
                                {
                                    b2.Property<Guid>("ProductVariantId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("DiscountType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("ProductVariantId");

                                    b2.ToTable("variants", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ProductVariantId");
                                });

                            b1.OwnsOne("KShop.Commerce.ProductManagement.Domain.ProductAggregate.Price", "Price", b2 =>
                                {
                                    b2.Property<Guid>("ProductVariantId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)");

                                    b2.HasKey("ProductVariantId");

                                    b2.ToTable("variants", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ProductVariantId");
                                });

                            b1.Navigation("Discount");

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("_variants");
                });
#pragma warning restore 612, 618
        }
    }
}
