<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KShop.Commerce.OrderManagement.Domain</RootNamespace>
    <AssemblyName>KShop.Commerce.OrderManagement.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="OrderStatusExtensions.cs"
             DependentUpon="OrderStatus.cs"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="ReferenceTrimmer" Version="3.5.9"/>
  </ItemGroup>
</Project>
