<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KShop.Commerce.ProductManagement.Application</RootNamespace>
    <AssemblyName>KShop.Commerce.ProductManagement.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj"/>
    <Compile Update="ProductServices\CreateProductCommandHandler.cs"
             DependentUpon="CreateProductCommand.cs"/>

    <Compile Update="ProductServices\RemoveProductCommandHandler.cs"
             DependentUpon="RemoveProductCommand.cs"/>

    <Compile Update="ProductServices\UpdateProductCommandHandler.cs"
             DependentUpon="UpdateProductCommand.cs"/>

  </ItemGroup>

</Project>
