<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <RootNamespace>KShop.Commerce.SharedKernel.ProductAggregateVO</RootNamespace>
      <AssemblyName>KShop.Commerce.SharedKernel.ProductAggregateVO</AssemblyName>
    </PropertyGroup>
  <ItemGroup>
    <Compile Update="ProductAggregate\DiscountType.cs">
      <DependentUpon>Discount.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
