<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KShop.Commerce.ProductManagement.Infrastructure</RootNamespace>
    <AssemblyName>KShop.Commerce.ProductManagement.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj"/>
  </ItemGroup>

</Project>
